### ISSUE TITLE
【求助】组播源突然无法正常播放

### ISSUE THREAD

**Issue by A1exMinatoooo** [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List#27]
使用环境：深圳电信 光棒VLAN透传使用OpenWRT拨号并运行udpxy

之前一直可以使用开发者的组播源正常播放，但是从上周开始所有地址均不传输视频流，udpxy后台throughput显示为N/A

![telegram-cloud-photo-size-5-6280500707115251033-y](https://user-images.githubusercontent.com/21982749/217990482-287d0866-7bb8-4e9d-808d-cc85133d6468.jpg)

请问有人碰到类似的情况么，有何解决思路？

**Comment by zhu-jie** [comment]
我也遇到相同的问题了，暂未解决

**Comment by heliosliu** [comment]
不是地址没用了，而是电信根本没有给组播信号

**Comment by heliosliu** [comment]
电信现在都是单播，也就是说用rtsp的那个地址。不信你对你的电视机顶盒去抓包，你会发现盒子都是用单播地址了。组播信号已经没了，所以有地址也没有用。

**Comment by zhu-jie** [comment]
我这边广州电信，验证时可以了组播也是可行的 现在就看着很顺畅

**Comment by A1exMinatoooo** [comment]
> 电信现在都是单播，也就是说用rtsp的那个地址。不信你对你的电视机顶盒去抓包，你会发现盒子都是用单播地址了。组播信号已经没了，所以有地址也没有用。

我全链路重启了一下组播又好用了

**Comment by heliosliu** [comment]
能把你的iptv拨号获取到的ip段发我下不？我之前怀疑有些服务器其实没有干掉组播，但是我连续拨号拨了好几天，都没有拨到有组播信号的服务器。




枫林绵雨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 中午1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List] 【求助】组播源突然无法正常播放 (Issue #27)





  
电信现在都是单播，也就是说用rtsp的那个地址。不信你对你的电视机顶盒去抓包，你会发现盒子都是用单播地址了。组播信号已经没了，所以有地址也没有用。
  
我全链路重启了一下组播又好用了

**Comment by heliosliu** [comment]
ip段就行了，最后的地址用0代替

**Comment by zhu-jie** [comment]
> 能把你的iptv拨号获取到的ip段发我下不？我之前怀疑有些服务器其实没有干掉组播，但是我连续拨号拨了好几天，都没有拨到有组播信号的服务器。 枫林绵雨 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List" ***@***.***&gt;; 发送时间:&nbsp;2023年4月16日(星期天) 中午1:27 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List] 【求助】组播源突然无法正常播放 (Issue #27) 电信现在都是单播，也就是说用rtsp的那个地址。不信你对你的电视机顶盒去抓包，你会发现盒子都是用单播地址了。组播信号已经没了，所以有地址也没有用。 我全链路重启了一下组播又好用了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;



> ip段就行了，最后的地址用0代替

10.168.62.0/32这是广州的，我的情况双线都PPPOE拨号的方式

**Comment by heliosliu** [comment]
所以你是深圳电信还是广州电信？深圳电信怎么取到广州的IP？
我是深圳电信的，也是双线pppoe拨号。




枫林绵雨
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 中午1:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List] 【求助】组播源突然无法正常播放 (Issue #27)





  
能把你的iptv拨号获取到的ip段发我下不？我之前怀疑有些服务器其实没有干掉组播，但是我连续拨号拨了好几天，都没有拨到有组播信号的服务器。 枫林绵雨 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List" @.&gt;; 发送时间:&nbsp;2023年4月16日(星期天) 中午1:27 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Tzwcard/ChinaTelecom-GuangdongIPTV-RTP-List] 【求助】组播源突然无法正常播放 (Issue #27) 电信现在都是单播，也就是说用rtsp的那个地址。不信你对你的电视机顶盒去抓包，你会发现盒子都是用单播地址了。组播信号已经没了，所以有地址也没有用。 我全链路重启了一下组播又好用了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
   
ip段就行了，最后的地址用0代替
  
10.168.62.0/32这是广州的，我的情况双线都PPPOE拨号的方式

**Comment by heliosliu** [comment]
哦，我说的是需要楼主的ip段，我想知道那个ip段有组播信号，我用脚本拨下看能不能拨到这个ip段。深圳电信肯定有些服务器忘记关组播了

**Comment by A1exMinatoooo** [comment]
> 哦，我说的是需要楼主的ip段，我想知道那个ip段有组播信号，我用脚本拨下看能不能拨到这个ip段。深圳电信肯定有些服务器忘记关组播了

10.164

**Comment by heliosliu** [comment]
> > 哦，我说的是需要楼主的ip段，我想知道那个ip段有组播信号，我用脚本拨下看能不能拨到这个ip段。深圳电信肯定有些服务器忘记关组播了
> 
> 10.164

感谢老板，不过能否把第三段也给下

**Comment by A1exMinatoooo** [comment]
> > > 哦，我说的是需要楼主的ip段，我想知道那个ip段有组播信号，我用脚本拨下看能不能拨到这个ip段。深圳电信肯定有些服务器忘记关组播了
> > 
> > 
> > 10.164
> 
> 感谢老板，不过能否把第三段也给下

`10.164.30.0`

**Comment by heliosliu** [comment]
> > > > 哦，我说的是需要楼主的ip段，我想知道那个ip段有组播信号，我用脚本拨下看能不能拨到这个ip段。深圳电信肯定有些服务器忘记关组播了
> > > 
> > > 
> > > 10.164
> > 
> > 
> > 感谢老板，不过能否把第三段也给下
> 
> `10.164.30.0`

非常感谢。

**Comment by heliosliu** [comment]
> > > > 哦，我说的是需要楼主的ip段，我想知道那个ip段有组播信号，我用脚本拨下看能不能拨到这个ip段。深圳电信肯定有些服务器忘记关组播了
> > > 
> > > 
> > > 10.164
> > 
> > 
> > 感谢老板，不过能否把第三段也给下
> 
> `10.164.30.0`

可否帮给个网关地址？我尝试用10.164.30.1做网关地址，好像没有这个网关
